### ISSUE TITLE
Error: The field 'iKey' is required but not present on source

### ISSUE THREAD

**Issue by koistya** [Microsoft/AppInsights-node.js#9]
```
Missing required field specification: The field 'iKey' is required but not present on source
```

**Comment by scsouthw** [comment]
Thanks for the feedback. Can you share more detail about how you're getting this error? I'm not able to repro that error message.

An instrumentation key is required to use the SDK so that sounds like the root issue, more info here: https://github.com/Microsoft/AppInsights-Home/wiki#getting-an-application-insights-instrumentation-key

**Comment by koistya** [comment]
What kind of info do you need? I'm able to reproduce this issue in both local environment (Windows 8.1, Node 0.12.0) and in Azure Websites. I'm providing instrumentation key with `APPINSIGHTS_INSTRUMENTATION_KEY` environment variable. If I don't provide it at all, it displays "Instrumentation key not found" error:

https://github.com/Microsoft/AppInsights-node.js/blob/master/applicationInsights.ts#L32

**Comment by scsouthw** [comment]
I see, thanks for the info. The code that throws that error is in the data-contract validation. In order to throw that error the instrumentation key would need to be undefined on a telemetry object that is about to be serialized.
```javascript
for (var field in source.aiDataContract) {
    var isRequired = source.aiDataContract[field];

    // this must be evaluated false to throw the error you're seeing
    var isPresent = source[field] !== undefined; 

    if (isRequired && !isPresent) {
        _InternalLogging.throwInternalUserActionable(
            LoggingSeverity.CRITICAL,
            "Missing required field specification: The field '" + field + "' is required but not present on source");
```
I am able to repro if I set the `APPINSIGHTS_INSTRUMENTATION_KEY` environment variable, then set it to undefined after instantiating.
```javascript
var AppInsights = require('applicationinsights');
var appInsights = new AppInsights();
appInsights.config.instrumentationKey = undefined;
appInsights.trackEvent("test");
```
